
export const cameras: string[] = [
  'Canon AE-1 - Analog - Soft warm contrast, 70s classic, light chrome.',
  'Canon EOS R6 Mark II - Digital Mirrorless - Universal balance of color and dynamics, clean skin-tone.',
  'Canon EOS 5D Mark IV - Digital DSLR - Cinematic color rendering, stable tone.',
  'Nikon F3 - Analog - Cold vintage tone, saturated shadows, 80s character.',
  'Nikon Z6 II - Digital Mirrorless - Sharp contrast, realistic color, neutral style.',
  'Nikon FM2 - Analog - Classic silver-gray grain, 1980s retro magazine look.',
  'Sony α7 III (Alpha 7 III) - Mirrorless Full-frame - Universal "film-look", ideal for retro LUTs.',
  'Sony α7C II - Compact Mirrorless - Soft bokeh, color close to movie frames.',
  'Fujifilm X100V - Digital Compact - Fuji film emulation, soft chrome, "nostalgic" light.',
  'Fujifilm X-T30 II - Mirrorless - Warm skin tones, "film-like" digital style.',
  'Fujifilm GFX 50R - Medium Format - Deep detail, cinematic volume.',
  'Panasonic Lumix GH6 - Video-oriented - Clean color and light control — suitable for films.',
  'Panasonic Lumix G100D - Compact - Balance for vlogs, saturated bright scenes.',
  'Olympus OM-1 - Analog - Smooth contrast, vintage softness.',
  'Olympus PEN-F (Digital) - Digital Retro - Light grain, retro-film style color.',
  'Ricoh GR IIIx - Compact - Contrasty street photography, sharpness and dynamics.',
  'Leica M6 - Analog (Germany) - Clean geometry, cinematic texture.',
  'Leica Q2 - Digital Full-frame - Crystal clear but soft color — high-end look.',
  'Contax T2 - Analog Compact - Iconic 90s look, cool balance, "fashion grain".',
  'Minolta SRT-101 - Analog - Clean texture, neutral palette, old-style contrast.',
  'Pentax K1000 - Analog - Pure film character, slightly faded colors.',
  'Yashica T4 - Analog - Legendary point-and-shoot with a "magazine" style.',
  'Hasselblad 500CM - Medium Format (Sweden) - Soft focus, ideal for cinematic portraits.',
  'Kyocera Samurai X3.0 - Semi-automatic - 90s vintage, saturated blues and reds.',
  'Polaroid SX-70 - Instant - Warm, soft, fading vintage color.',
];
