
export const filmTypes: string[] = [
  'Kodak Portra 400 - Color - Warm skin tones, soft contrast, cinematic realism.',
  'Kodak Portra 160 - Color - Light, pastel, light film with soft color.',
  'Kodak Portra 800 - Color - Bright contrast, warm tones, muted grain.',
  'Kodak Ektar 100 - Color - Clean, saturated colors, landscape style.',
  'Kodak Gold 200 - Color - Warm sunny color rendering, retro home vibe.',
  'Kodak Ultramax 400 - Color - Contrasty, bright, light "tourist" shade.',
  'Kodak ColorPlus 200 - Color - Soft faded tone, 90s vintage.',
  'Fujifilm Superia X-TRA 400 - Color - Green-blue tint, fresh and cool.',
  'Fujifilm Pro 400H - Color - Neutral shadows, soft pastels, natural skin.',
  'Fujifilm Velvia 50 - Color - Very high saturation, cinematic landscape, HDR effect.',
  'Fujifilm Provia 100F - Color - Cool palette, blue and purple accents.',
  'Fujifilm Natura 1600 - Color - Grainy, "night" with muted light.',
  'Cinestill 800T - Color - Cinematic night, neon glow, cool lights (Tungsten).',
  'Cinestill 50D - Color - Cinematic daylight, clean skin-tone.',
  'Cinestill BwXX - B&W - Coarse film grain, dark 60s cinema.',
  'Ilford HP5 Plus 400 - B&W - Classic grain, documentary style.',
  'Ilford Delta 3200 - B&W - Very grainy, atmospheric, dark scenes.',
  'Ilford Pan F Plus 50 - B&W - Super clean detail, soft light.',
  'Rollei Retro 80S - B&W - Contrasty, deep shadows, solid lines.',
  'Agfa Vista 200 - Color - Light purple, 2000s vintage style.',
  'Lomography Color Negative 800 - Color - Surreal colors, retro shifts.',
  'Lomography Metropolis - Color - Desaturation, gray-yellow tones, industrial style.',
  'Revolog Kolor - Color - Artificial gradient (purple-orange), art effect.',
  'Adox Color Mission 200 - Color - Balanced warm grain, modern retro.',
  'Rera Pan 400 (Japan) - B&W - Contrasty Japanese B&W, hard graphic style.',
];
