import { z } from "zod";

export const PromptTypeSchema = z.enum(["artistic", "json"]);
export type PromptType = z.infer<typeof PromptTypeSchema>;

export const CreationTypeSchema = z.enum(["inScene", "studio"]);
export type CreationType = z.infer<typeof CreationTypeSchema>;

// For form validation
export const CharacterFormSchema = z.object({
  description: z.string().min(1, "Description is required."),
  artStyle: z.string().optional().default(''),
  cameraAngle: z.string().optional().default(''),
  lightingStyle: z.string().optional().default(''),
  camera: z.string().optional().default(''),
  filmType: z.string().optional().default(''),
  promptType: PromptTypeSchema.default("artistic"),
  creationType: CreationTypeSchema.default("inScene"),
});
export type CharacterFormData = z.infer<typeof CharacterFormSchema>;

// For storage
export type Character = CharacterFormData & {
  id: string;
  name: string; // Extracted by AI
  appearanceDescription: string; // Generated by AI
  prompt: string;
  createdAt: string; // Use ISO string for serialization
};

// For form validation
export const SceneFormSchema = z.object({
  sceneDescription: z.string().min(1, "Scene description is required."),
  characterId: z.string().optional(),
  outfitId: z.string().optional(),
  artStyle: z.string().optional().default(''),
  cameraAngle: z.string().optional().default(''),
  lightingStyle: z.string().optional().default(''),
  camera: z.string().optional().default(''),
  filmType: z.string().optional().default(''),
  promptType: PromptTypeSchema.default("artistic"),
});
export type SceneFormData = z.infer<typeof SceneFormSchema>;

// For storage
export type Scene = SceneFormData & {
  id: string;
  prompt: string;
  createdAt: string; // Use ISO string for serialization
};

// For Outfit Generation
export const OutfitFormSchema = z.object({
    characterId: z.string().min(1, "A character must be selected."),
    description: z.string().min(1, "Outfit description is required."),
    artStyle: z.string().optional(),
});
export type OutfitFormData = z.infer<typeof OutfitFormSchema>;

export type Outfit = OutfitFormData & {
    id: string;
    name: string;
    prompt: string;
    createdAt: string;
};
    